accounts/urls.py
from django.urls import path
from accounts import views
urlpatterns = [
    path('login/', views.UserLogin, name="ingia"),
    path('logout/', views.logoutUser, name="toka"),
]

mtaawangu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mtendaji import views
from ujumbe import views as ujumbe_views
from mwenyekiti import views as mwenyekiti_views
from mjumbe import views as mjumbe_views
from staff import views as staff_views
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # dashibodi za users
    path('mwenyekiti/', mwenyekiti_views.dashboard, name="mwenyekiti-dashibodi"),
    path('mjumbe/', mjumbe_views.dashboard, name="mjumbe-dashibodi"),
    path('staff/', staff_views.dashboard, name="staff-dashibodi"),
    path('', views.dashboard, name="mtendaji-dashibodi"),

    # UTUMAJI WA UJUMBE PAMOJA NA ORODHA MBALI MBALI ZA JUMBE KWA UMMA ZA MTENDAJI
    path('mtendaji-tuma-kwa-mtaa/', views.tuma_kwa_mtaa, name="mtendaji-tuma-kwa-mtaa"),
    path('mtendaji-tuma-kwa-kata/', views.tuma_kwa_kata, name="mtendaji-tuma-kwa-kata"),
    path('mtendaji-tuma-kwa-barozi/', views.tuma_kwa_barozi, name="mtendaji-tuma-kwa-barozi"),
    path('mtendaji-tuma-ujumbe-kwa-mtaa/', views.tuma_ujumbe_kwa_mtaa, name="mtendaji-tuma-ujumbe-kwa-mtaa"),
    path('mtendaji-tuma-ujumbe-kwa-kata/', views.tuma_ujumbe_kwa_kata, name="mtendaji-tuma-ujumbe-kwa-kata"),
    path('mtendaji-tuma-ujumbe-kwa-barozi/', views.tuma_ujumbe_kwa_barozi, name="mtendaji-tuma-ujumbe-kwa-barozi"),
    path('mtendaji-jumbe/tuma-ujumbe/', views.tuma_ujumbe, name="mtendaji-tuma-ujumbe"),
    path('mtendaji-jumbe/orodha-ya-jumbe/', views.orodha_ya_jumbe, name="mtendaji-orodha-ya-jumbe"),
    path('mtendaji-jumbe-zilizotumwa/', views.orodha_ya_jumbe_zilizotumwa, name="mtendaji-jumbe-zilizotumwa"),


    # UTUMAJI WA UJUMBE PAMOJA NA ORODHA MBALI MBALI ZA JUMBE KWA UMMA ZA MWENYEKITI
    path('mwenyekiti-tuma-kwa-mtaa/', mwenyekiti_views.tuma_kwa_mtaa, name="mwenyekiti-tuma-kwa-mtaa"),
    path('mwenyekiti-tuma-kwa-kata/', mwenyekiti_views.tuma_kwa_kata, name="mwenyekiti-tuma-kwa-kata"),
    path('mwenyekiti-tuma-kwa-barozi/', mwenyekiti_views.tuma_kwa_barozi, name="mwenyekiti-tuma-kwa-barozi"),
    path('mwenyekiti-tuma-ujumbe-kwa-mtaa/', mwenyekiti_views.tuma_ujumbe_kwa_mtaa, name="mwenyekiti-tuma-ujumbe-kwa-mtaa"),
    path('mwenyekiti-tuma-ujumbe-kwa-kata/', mwenyekiti_views.tuma_ujumbe_kwa_kata, name="mwenyekiti-tuma-ujumbe-kwa-kata"),
    path('mwenyekiti-tuma-ujumbe-kwa-barozi/', mwenyekiti_views.tuma_ujumbe_kwa_barozi, name="mwenyekiti-tuma-ujumbe-kwa-barozi"),
    path('mwenyekiti-jumbe/tuma-ujumbe/', mwenyekiti_views.tuma_ujumbe, name="mwenyekiti-tuma-ujumbe"),
    path('mwenyekiti-jumbe/orodha-ya-jumbe/', mwenyekiti_views.orodha_ya_jumbe, name="mwenyekiti-orodha-ya-jumbe"),
    path('mwenyekiti-jumbe-zilizotumwa/', mwenyekiti_views.orodha_ya_jumbe_zilizotumwa, name="mwenyekiti-jumbe-zilizotumwa"),


    # UTUMAJI WA UJUMBE PAMOJA NA ORODHA MBALI MBALI ZA JUMBE KWA UMMA ZA MJUMBE
    path('mjumbe-tuma-kwa-mtaa/', mjumbe_views.tuma_kwa_mtaa, name="mjumbe-tuma-kwa-mtaa"),
    path('mjumbe-tuma-kwa-kata/', mjumbe_views.tuma_kwa_kata, name="mjumbe-tuma-kwa-kata"),
    path('mjumbe-tuma-kwa-barozi/', mjumbe_views.tuma_kwa_barozi, name="mjumbe-tuma-kwa-barozi"),
    path('mjumbe-tuma-ujumbe-kwa-mtaa/', mjumbe_views.tuma_ujumbe_kwa_mtaa, name="mjumbe-tuma-ujumbe-kwa-mtaa"),
    path('mjumbe-tuma-ujumbe-kwa-kata/', mjumbe_views.tuma_ujumbe_kwa_kata, name="mjumbe-tuma-ujumbe-kwa-kata"),
    path('mjumbe-tuma-ujumbe-kwa-barozi/', mjumbe_views.tuma_ujumbe_kwa_barozi, name="mjumbe-tuma-ujumbe-kwa-barozi"),
    path('mjumbe-jumbe/tuma-ujumbe/', mjumbe_views.tuma_ujumbe, name="mjumbe-tuma-ujumbe"),
    path('mjumbe-jumbe/orodha-ya-jumbe/', mjumbe_views.orodha_ya_jumbe, name="mjumbe-orodha-ya-jumbe"),
    path('mjumbe-jumbe-zilizotumwa/', mjumbe_views.orodha_ya_jumbe_zilizotumwa, name="mjumbe-jumbe-zilizotumwa"),



    # UTUMAJI WA UJUMBE PAMOJA NA ORODHA MBALI MBALI ZA JUMBE KWA UMMA ZA STAFF
    path('staff-tuma-kwa-mtaa/', staff_views.tuma_kwa_mtaa, name="staff-tuma-kwa-mtaa"),
    path('staff-tuma-kwa-kata/', staff_views.tuma_kwa_kata, name="staff-tuma-kwa-kata"),
    path('staff-tuma-kwa-barozi/', staff_views.tuma_kwa_barozi, name="staff-tuma-kwa-barozi"),
    path('staff-tuma-ujumbe-kwa-mtaa/', staff_views.tuma_ujumbe_kwa_mtaa, name="staff-tuma-ujumbe-kwa-mtaa"),
    path('staff-tuma-ujumbe-kwa-kata/', staff_views.tuma_ujumbe_kwa_kata, name="staff-tuma-ujumbe-kwa-kata"),
    path('staff-tuma-ujumbe-kwa-barozi/', staff_views.tuma_ujumbe_kwa_barozi, name="staff-tuma-ujumbe-kwa-barozi"),
    path('staff-jumbe/tuma-ujumbe/', staff_views.tuma_ujumbe, name="staff-tuma-ujumbe"),
    path('staff-jumbe/orodha-ya-jumbe/', staff_views.orodha_ya_jumbe, name="staff-orodha-ya-jumbe"),
    path('staff-jumbe-zilizotumwa/', staff_views.orodha_ya_jumbe_zilizotumwa, name="staff-jumbe-zilizotumwa"),
   
    path('staff-sajiri-mtendaji/<int:pk>/', staff_views.kusajiri_mtendaji, name="sajiri-mtendaji"),
    path('mtendaji-akaunti/', staff_views.mtendaji_registration, name="register-mtendaji"),
    path('hifadhi-mtendaji/', staff_views.hifadhi_mtendaji, name="hifadhi-mtendaji"),

    path('staff-sajiri-mwenyekiti/<int:pk>/', staff_views.kusajiri_mwenyekiti, name="sajiri-mwenyekiti"),
    path('mwenyekiti-akaunti/', staff_views.mwenyekiti_registration, name="register-mwenyekiti"),
    path('hifadhi-mwenyekiti/', staff_views.hifadhi_mwenyekiti, name="hifadhi-mwenyekiti"),

    path('staff-sajiri-mjumbe/<int:pk>/', staff_views.kusajiri_mjumbe, name="sajiri-mjumbe"),
    path('mjumbe-akaunti/', staff_views.mjumbe_registration, name="register-mjumbe"),
    path('hifadhi-mjumbe/', staff_views.hifadhi_mjumbe, name="hifadhi-mjumbe"),




    # UTUMAJI UJUMBE AJAX CALL ZA MTENDAJI
    path('mtendaji-hifadhi-jumbe-zilizotumwa-ajax/', views.hifadhi_jumbe_zilizotumwa_ajax, name="mtendaji-hifadhi-jumbe-zilizotumwa-ajax"),
    path('mwenyekiti-hifadhi-jumbe-zilizotumwa-ajax/', mwenyekiti_views.hifadhi_jumbe_zilizotumwa_ajax, name="mwenyekiti-hifadhi-jumbe-zilizotumwa-ajax"),
    path('mjumbe-hifadhi-jumbe-zilizotumwa-ajax/', mjumbe_views.hifadhi_jumbe_zilizotumwa_ajax, name="mjumbe-hifadhi-jumbe-zilizotumwa-ajax"),
    path('staff-hifadhi-jumbe-zilizotumwa-ajax/', staff_views.hifadhi_jumbe_zilizotumwa_ajax, name="staff-hifadhi-jumbe-zilizotumwa-ajax"),

    # SEHEMU YA ORODHA YA WANANCHI, NA USAJIRI WA WANANCHI
    path('wananchi/', ujumbe_views.orodha_ya_wananchi, name="orodha-ya-wananchi"),
    path('sajiri-mwananchi/', ujumbe_views.kusajiri_mwananchi, name="sajiri-mwananchi"),
    path('hifadhi-mwananchi/', ujumbe_views.hifadhi_mwananchi, name="hifadhi-mwananchi"),

    # NCHI, MIKOA, WILAYA, KATA, NA MITAA AJAX CALL 
    path('mikoa-na-ajax/', ujumbe_views.mikoa_na_ajax, name="mikoa-na-ajax"),
    path('wilaya-na-ajax/', ujumbe_views.wilaya_na_ajax, name="wilaya-na-ajax"),
    path('kata-na-ajax/', ujumbe_views.kata_na_ajax, name="kata-na-ajax"),
    path('mtaa-na-ajax/', ujumbe_views.mtaa_na_ajax, name="mtaa-na-ajax"),
    path('ubarozi-na-ajax/', ujumbe_views.ubarozi_na_ajax, name="ubarozi-na-ajax"),

    # USAJIRI WA UBAROZI, KATA, WILAYA, MIKOA, NA NCHI
    path('sajiri-kata/', ujumbe_views.sajiriKata, name="sajiri-kata"),
    path('sajiri-mkoa/', ujumbe_views.sajiriMkoa, name="sajiri-mkoa"),


    path('accounts/', include('accounts.urls')),

    path('404/', accounts_views.not_found, name='404'),

    path('password-change/', accounts_views.PasswordsChangeView.as_view(template_name="settings/password_change.html"), name="change_password"),
    path('success/', accounts_views.success_page, name="success_page"),
    path('password_changed_success/', accounts_views.password_changed_success, name="success_password"),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mwenyekiti/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User



class Nchi(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.jina

    class Meta:
        verbose_name_plural = 'Nchi'


class Mkoa(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)
    nchi = models.ForeignKey('Nchi', on_delete=models.CASCADE, default='Tanzania', related_name="mkoa_ya_nchi")

    def __str__(self):
        return self.jina


    class Meta:
        verbose_name_plural = 'Mikoa'


class Wilaya(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)
    mkoa = models.ForeignKey('Mkoa', on_delete=models.CASCADE, related_name="wilaya_mikoa")

    def __str__(self):
        return self.jina

    class Meta:
        verbose_name_plural = 'Wilaya'



class Kata(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)
    wilaya = models.ForeignKey('Wilaya', on_delete=models.CASCADE, null=True, blank=True, related_name="kata_wilaya")

    def __str__(self):
        return self.jina

    class Meta:
        verbose_name_plural = 'Kata'


class Mtaa(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)
    kata = models.ForeignKey('Kata', on_delete=models.CASCADE, related_name="mitaa_kata")

    def __str__(self):
        return self.jina

    class Meta:
        verbose_name_plural = 'Mitaa'


class NyumbaKumi(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)
    mtaa = models.ForeignKey('Mtaa', on_delete=models.CASCADE, null=True, related_name="barozi_mitaa")

    def __str__(self):
        return self.jina

    class Meta:
        verbose_name_plural = 'NyumbaKumi'


class Mtendaji(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    jina = models.CharField(max_length=200, null=True, blank=True)
    nambari_ya_simu = models.CharField(max_length=200, null=True, blank=True)
    jinsia = models.CharField(max_length=225, null=True)
    barua_pepe = models.CharField(max_length=200, null=True, blank=True)
    mtaa = models.ForeignKey('Mtaa', on_delete=models.CASCADE, null=True, blank=True, related_name="mtendaji_mtaa")
    kata = models.ForeignKey('Kata', on_delete=models.CASCADE, null=True, blank=True, related_name="mtendaji_kata")
    wilaya = models.ForeignKey('Wilaya', on_delete=models.CASCADE, null=True, blank=True, related_name="mtendaji_wilaya")
    mkoa = models.ForeignKey('Mkoa', on_delete=models.CASCADE, null=True, blank=True, related_name="mtendaji_mkoa")
    nchi = models.ForeignKey('Nchi', on_delete=models.CASCADE, null=True, blank=True, related_name="mtendaji_nchi")
    barozi = models.ForeignKey('NyumbaKumi', on_delete=models.CASCADE, null=True, blank=True, related_name="mtendaji_ubarozi")

    class Meta:
        verbose_name_plural = 'Watendaji'

    def __str__(self):
        return self.jina


class Mwenyekiti(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    mtendaji = models.ForeignKey('Mtendaji', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_mtendaji")
    jina = models.CharField(max_length=200, null=True, blank=True)
    nambari_ya_simu = models.CharField(max_length=200, null=True, blank=True)
    jinsia = models.CharField(max_length=225, null=True)
    barua_pepe = models.CharField(max_length=200, null=True, blank=True)
    nchi = models.ForeignKey('Nchi', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_nchi")
    mkoa = models.ForeignKey('Mkoa', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_mkoa")
    wilaya = models.ForeignKey('Wilaya', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_wilaya")
    kata = models.ForeignKey('Kata', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_kata")
    mtaa = models.ForeignKey('Mtaa', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_mtaa")
    barozi = models.ForeignKey('NyumbaKumi', on_delete=models.CASCADE, null=True, blank=True, related_name="mwenyekiti_nyumba_kumi")
    
    class Meta:
        verbose_name_plural = 'Wenyeviti'

    def __str__(self):
        return self.jina


class Mjumbe(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    mtendaji = models.ForeignKey('Mtendaji', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_mtendaji")
    mwenyekiti = models.ForeignKey('Mwenyekiti', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_mwenyekiti")
    jina = models.CharField(max_length=200, null=True, blank=True)
    jinsia = models.CharField(max_length=225, null=True)
    nambari_ya_simu = models.CharField(max_length=200, null=True, blank=True)
    barua_pepe = models.CharField(max_length=200, null=True, blank=True)
    nchi = models.ForeignKey('Nchi', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_nchi")
    mkoa = models.ForeignKey('Mkoa', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_mkoa")
    wilaya = models.ForeignKey('Wilaya', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_wilaya")
    kata = models.ForeignKey('Kata', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_kata")
    mtaa = models.ForeignKey('Mtaa', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_mtaa")
    barozi = models.ForeignKey('NyumbaKumi', on_delete=models.CASCADE, null=True, blank=True, related_name="mjumbe_barozi")
    class Meta:
        verbose_name_plural = 'Wajumbe'

    def __str__(self):
        return self.jina



class Mwananchi(models.Model):
    jina = models.CharField(max_length=200, null=True, blank=True)
    mtendaji = models.ForeignKey('Mtendaji', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_mtendaji")
    mjumbe = models.ForeignKey('Mjumbe', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_mjumbe")
    nambari_ya_simu = models.CharField(max_length=200, null=True, blank=True)
    barua_pepe = models.CharField(max_length=200, null=True, blank=True)
    jinsia = models.CharField(max_length=225, null=True)
    nchi = models.ForeignKey('Nchi', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_nchi")
    mkoa = models.ForeignKey('Mkoa', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_mkoa")
    wilaya = models.ForeignKey('Wilaya', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_wilaya")
    kata = models.ForeignKey('Kata', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_kata")
    mtaa = models.ForeignKey('Mtaa', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_mtaa")
    barozi = models.ForeignKey('NyumbaKumi', on_delete=models.CASCADE, null=True, blank=True, related_name="mwananchi_barozi")

    class Meta:
        verbose_name_plural = 'Wananchi'


    def __str__(self):
        return self.jina






class Sponsor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

templates/mwenyekiti/orodha.html
{% extends 'base/index.html' %}
{% block title %}Meseji zangu zote{% endblock %}
{% load static %}

{% block page %}Meseji zangu zote{% endblock page %}
{% block slogan %}orodha ya Meseji zangu zote{% endblock slogan %} 

{% block style %}
    <style>
        .hide-accept-form {
            display: none;
        }
        .hide-response-form {
            display: none;
        }
        .hide-add-form {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}
<div class="page-header">
    <div class="page-title">

    </div>
    <!-- <div class="page-btn">
        <a href="{% url 'mwenyekiti-tuma-kwa-kata' %}" class="btn btn-added"><img src="{% static 'assets/img/icons/plus.svg' %}" alt="img" class="me-1">tuma kwa kata</a>
    </div> -->
    <div class="page-btn">
        <a href="{% url 'mwenyekiti-tuma-kwa-mtaa' %}" class="btn btn-added"><img src="{% static 'assets/img/icons/plus.svg' %}" alt="img" class="me-1">tuma kwa mtaa</a>
    </div>
    <div class="page-btn">
        <a href="{% url 'mwenyekiti-tuma-kwa-barozi' %}" class="btn btn-added"><img src="{% static 'assets/img/icons/plus.svg' %}" alt="img" class="me-1">tuma kwa ubarozi</a>
    </div>
</div>

<div class="card">
    <div class="card-body">
    <div class="table-top">
    <div class="search-set">
    <div class="search-path">
    <a class="btn btn-filter" id="filter_search">
        <img src="{% static 'assets/img/icons/filter.svg' %}" alt="img">
        <span><img src="{% static 'assets/img/icons/closes.svg' %}" alt="img"></span>
    </a>
    </div>
    <div class="search-input">
    <a class="btn btn-searchset"><img src="{% static 'assets/img/icons/search-white.svg' %}" alt="img"></a>
    </div>
        {% include 'partials/_messages.html' %}
    </div>
    <div class="wordset">'
    </div>
    </div>
    
    <div class="card mb-0" id="filter_inputs">
    <div class="card-body pb-0">
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 d-flex justify-content-between">
            <div class="form-group">
                <select name="status" id="id_status" class="form-control">
                    <option value="arrived" class="form-control">arrived</option>
                </select>
                
            </div>
            <div class="form-group">
                <input type="date" id="id_date" name="date" placeholder="Date" class="form-control">
            </div>
            <div class="form-group">
                <input type="time" name="time" id="id_time" placeholder="Time" class="form-control">
            </div>

            <div class="form-group">
                <input name="note" id="id_note"  placeholder="Note" class="form-control">
            </div>
            <div class="form-group">
                <select name="terminal" id="id_terminal" class="form-control">
                    <option value="CAN - Guanzhou">CAN - Guanzhou</option>
                    <option value="HKG - HongKong">HKG - HongKong</option>
                    <option value="DAR - Dar es salaam">DAR - Dar es salaam</option>
                    <option value="DXB - Dubai">DXB - Dubai</option>
                    <option value="NBO - Nairobi">NBO - Nairobi</option>
                    <option value="SHJ - Sharjah">SHJ - Sharjah</option>
                    <option value="JNB - Johanesburg">JNB - Johanesburg</option>
                    <option value="MCT - Muscat">MCT - Muscat</option>
                    <option value="BOM - Mumbai">BOM - Mumbai</option>
                    <option value="ADD - Addis Ababa">ADD - Addis Ababa</option>
                </select>
                
            </div>
            <div class="update-btn ml-3">
                <button type="submit" id="arrived_btn" class="btn btn-danger add_arrived_status" >save</button>
            </div>
        </div>
    </div>
    </div>
    </div>
    
    <div class="table-responsive">
    <table class="table  datanew">
    <thead>
    <tr>
    <th>
    <label class="checkboxs">
    <input type="checkbox" id="select-all">
    <span class="checkmarks"></span>
    </label>
    </th>
    <th>tarehe ya kutumwa </th>
    </tr>
    </thead>
    <tbody>
    {% for pc in jumbe %}
    <tr>
    <td>
    <label class="checkboxs">
    <input type="checkbox" name="awb_id[]" value="{{pc.id}}" id="arrived_status" class="arrived_status">
    <span class="checkmarks"></span>
    </label>
    </td>
    <td>{{pc.date_created}}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
  
  
</script>
{% endblock %}

templates/mwenyekiti/tuma_kwa_barozi.html
{% extends 'base/index.html' %}
{% load static %}
{% block title %}Chagua kata kutuma ujumbe{% endblock %}

{% block page %}Chagua kata{% endblock page %}
{% block slogan %}Chagua kata kutuma ujumbe{% endblock slogan %}    
 
{% block style %}
    <style>
        .hide-accept-form {
            display: none;
        }
        .hide-response-form {
            display: none;
        }
        .hide-add-form {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}

<div class="card">
<div class="card-body">
    {% include 'partials/_messages.html' %}
    <form action="{% url 'mwenyekiti-tuma-ujumbe-kwa-barozi' %}" method="post">
        {% csrf_token %}
        <div class="row">

            <div class="col-lg-3 col-sm-6 col-12">
                <div class="form-group">
                <label>Chagua Barozi</label>
                  <select required name="barozi" id="id_barozi" class="form-control">
                  {% for obj in barozi %}
                    <option name="barozi" value="{{obj}}" class="form-control">{{obj}}</option>
                  {% endfor %}
                </select>
                </div>
            </div>
           
        </div>
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <button type="submit" class="btn btn-submit me-2">ENDELEA</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock content %}
{% block script %}
<script>
  
</script>
{% endblock %}

templates/mwenyekiti/tuma_kwa_kata.html
{% extends 'base/index.html' %}
{% load static %}
{% block title %}Chagua kata kutuma ujumbe{% endblock %}

{% block page %}Chagua kata{% endblock page %}
{% block slogan %}Chagua kata kutuma ujumbe{% endblock slogan %}    
 
{% block style %}
    <style>
        .hide-accept-form {
            display: none;
        }
        .hide-response-form {
            display: none;
        }
        .hide-add-form {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}

<div class="card">
<div class="card-body">
    {% include 'partials/_messages.html' %}
    <form action="{% url 'mwenyekiti-tuma-ujumbe-kwa-kata' %}" method="post">
        {% csrf_token %}
        <div class="row">

            <div class="col-lg-3 col-sm-6 col-12">
                <div class="form-group">
                <label>Chagua Kata</label>
                  <select required name="kata" id="id_kata" class="form-control">
                    <option name="kata" value="{{kata}}" class="form-control">{{kata}}</option>
                </select>
                </div>
            </div>
           
        </div>
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <button type="submit" class="btn btn-submit me-2">ENDELEA</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock content %}
{% block script %}
<script>
  
</script>
{% endblock %}

templates/mwenyekiti/tuma_kwa_mtaa.html
{% extends 'base/index.html' %}
{% load static %}
{% block title %}Chagua mtaa kutuma ujumbe{% endblock %}

{% block page %}Chagua mtaa{% endblock page %}
{% block slogan %}Chagua mtaa kutuma ujumbe{% endblock slogan %}    
 
{% block style %}
    <style>
        .hide-accept-form {
            display: none;
        }
        .hide-response-form {
            display: none;
        }
        .hide-add-form {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}

<div class="card">
<div class="card-body">
    {% include 'partials/_messages.html' %}
    <form action="{% url 'mwenyekiti-tuma-ujumbe-kwa-mtaa' %}" method="post">
        {% csrf_token %}
        <div class="row">

            <div class="col-lg-3 col-sm-6 col-12">
                <div class="form-group">
                <label>Chagua Mtaa</label>
                  <select required name="mtaa" id="id_mtaa" class="form-control">
                    <option name="mtaa" value="{{mtaa}}" class="form-control">{{mtaa}}</option>
                </select>
                </div>
            </div>
           
        </div>
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <button type="submit" class="btn btn-submit me-2">ENDELEA</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock content %}
{% block script %}
<script>
  
</script>
{% endblock %}